# Generated by Django 5.1.4 on 2025-01-09 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="image",
            field=models.FilePathField(path="/projects/img"),
        ),
    ]
