# Generated by Django 5.1.4 on 2025-01-10 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0002_alter_project_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="image",
            field=models.CharField(max_length=100),
        ),
    ]
